dist: xenial
language: python
python:
    - 3.5
    - 3.6
    - 3.7
    - 3.8-dev
install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install -e .
script:
    - flake8
    - pytest --cov
after_success:
    - coveralls
